namespace Nop.Plugin.Payments.OpenEdge.HostPay;

public enum TransactionType
{
	CREDITSALE,
	CREDITRETURN,
	CREDITONLINECAPTURE,
	CREDITOFFLINECAPTURE,
	CREDITAUTH,
	CREDITUPDATE,
	CREDITVOID,
	DEBITSALE,
	DEBITRETURN,
	DEBITVOID,
	EBTSALE,
	EBTRETURN,
	EBTVOUCHERCLEAR,
	CHECKSALE,
	CHECKCREDIT,
	CHECKVERIFICATION,
	CHCKALIASCREATE,
	CHECKALIASLOOKUP,
	CHECKALIASDELETE,
	ALIASCREATE,
	ALIASUPDATE,
	ALIASLOOKUP,
	ALIASDELETE,
	QUERYPAYMENT
}
